name: notes-be

services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3001:80
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_DB_USER}:${NOTES_DB_PASSWORD}@notes_db/${NOTES_DB_NAME}
    networks:
      - notes-net
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    depends_on:
      - notes_db

  notes_db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: volume
        source: notes_data
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    networks:
      - notes-net

volumes:
  notes_data:

networks:
  notes-net:
